### ISSUE TITLE
Formatting issues during Table creation

### ISSUE THREAD

**Issue by grahulvg** [microsoft/roosterjs#1509]
**Describe the bug**
There is a formatting issue in table cells due to global css styles. This causes the table creation menu items to be misaigned
```css
* {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}
```

**To Reproduce**
Add the above global css style to code and open table creation menu

**Expected behavior**
Properly formatted table cells

**Screenshots**

<img width="537" alt="table" src="https://user-images.githubusercontent.com/122917644/212975346-f61ef395-c3be-40bd-8bce-5d6b38824d7d.png">

**Device Information**
All devices/browsers

**Additional context**
NA
